import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:async';
import 'dart:convert';

Future<List<Autogenerated>> load() async {
  final response = await http.get(Uri.parse(
      'https://www.metaweather.com/api/location/2122265/2022/01/19/'));

  if (response.statusCode == 200) {
    print(response.body);
    List<dynamic> jsons = jsonDecode(response.body);
    List<Autogenerated> result = [];
    for (var value in jsons) {
      result.add(Autogenerated.fromJson(value as Map<String, dynamic>));
    }
    return result;
  } else {
    throw Exception('Failed to load album');
  }
}

class Autogenerated {
  int id;
  String weatherStateName;
  String weatherStateAbbr;
  String windDirectionCompass;
  String created;
  String applicableDate;
  double minTemp;
  double maxTemp;
  double theTemp;
  double windSpeed;
  double windDirection;
  double airPressure;
  int humidity;
  double? visibility;
  int predictability;

  Autogenerated(
      {required this.id,
      required this.weatherStateName,
      required this.weatherStateAbbr,
      required this.windDirectionCompass,
      required this.created,
      required this.applicableDate,
      required this.minTemp,
      required this.maxTemp,
      required this.theTemp,
      required this.windSpeed,
      required this.windDirection,
      required this.airPressure,
      required this.humidity,
      required this.visibility,
      required this.predictability});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
        id: json['id'],
        weatherStateName: json['weather_state_name'],
        weatherStateAbbr: json['weather_state_abbr'],
        windDirectionCompass: json['wind_direction_compass'],
        created: json['created'],
        applicableDate: json['applicable_date'],
        minTemp: json['min_temp'],
        maxTemp: json['max_temp'],
        theTemp: json['the_temp'],
        windSpeed: json['wind_speed'],
        windDirection: json['wind_direction'],
        airPressure: json['air_pressure'],
        humidity: json['humidity'],
        visibility: json['visibility'],
        predictability: json['predictability']);
  }
}

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var officesList;

  @override
  void initState() {
    super.initState();
    officesList = load();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fetch Data Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Fetch Data Example'),
        ),
        body: Center(
          child: FutureBuilder<List<Autogenerated>>(
            future: officesList,
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                final List<Autogenerated> futureResult = snapshot.data!;
                if (futureResult.isEmpty) {
                  return Text(
                    "The result is empty!",
                    style: TextStyle(fontSize: 24),
                  );
                } else {
                  List<Widget> resultChildren = [];
                  for (var value in futureResult) {
                    resultChildren.add(Text(
                      "${value.applicableDate} -${value.weatherStateName} - ${value.theTemp}",
                      style: TextStyle(fontSize: 19),
                    ));
                  }

                  return ListView(
                    children: resultChildren,
                  );
                }
              } else if (snapshot.hasError) {
                return Text('${snapshot.error}');
              }

              // By default, show a loading spinner.
              return const CircularProgressIndicator();
            },
          ),
        ),
      ),
    );
  }
}
